---
title =  "sub_badges"
author =  "Afton Coombs"
date =  "1/13/2021"
output =  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

## Intro
These are mock-ups of sub badges made in R. :)

## Palettes
```{r make-palette}
bold_pal <-
  c("Dark Slate Blue" = "#54478c",
    "Sapphire Blue" = "#2c699a",
    "Blue Munsell" = "#048ba8",
    "Keppel" = "#0db39e",
    "Medium Aquamarine" = "#16db93",
    "Light Green" = "#83e377",
    "Inchworm" = "#b9e769",
    "Corn" = "#efea5a",
    "Maize Crayola" = "#f1c453",
    "Sandy Brown" = "#f29e4c")

pastel_pal <-
  c("Light Pink" = "#ffadad",
    "Deep Champagne" = "#ffd6a5",
    "Lemon Yellow Crayola" = "#fdffb6",
    "Tea Green" = "#caffbf",
    "Celeste" = "#9bf6ff",
    "Baby Blue Eyes" = "#a0c4ff",
    "Maximum Blue Purple" = "#bdb2ff",
    "Mauve" = "#ffc6ff",
    "Baby Powder" = "#fffffc")

shades::swatch(pastel_pal)
shades::swatch(bold_pal)
```

## General Sub Badge
```{r general-sub-badge}
set.seed(10)
general_sub_data <-
  data.frame(x = seq(1:20))
general_sub_data$y <- 
  general_sub_data$x + 
  runif(n = length(general_sub_data$x),
        max = 5)


ggplot2::ggplot(data = general_sub_data,
                mapping = ggplot2::aes(x = x, 
                                       y = y)) +
  ggplot2::geom_line(color = bold_pal[["Sapphire Blue"]],
                     size = 10) +
  # ggplot2::geom_text(mapping = ggplot2::aes(x = 10,
  #                                           y = 14,
  #                                           label = ("1")),
                     # size = 120) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5),
                 panel.background = 
                   ggplot2::element_rect(fill = pastel_pal[["Baby Powder"]]))
```

# Two Month Sub Badge
```{r two-month, options}
set.seed(10)
two_month_sub_data <-
  data.frame(x = rep(1, 3),
             y = c(4, 6, 5),
             type = seq(1, 3))

ggplot2::ggplot(data = two_month_sub_data,
                mapping = ggplot2::aes(x = x, 
                                       y = y, 
                                       fill = factor(type), 
                                       group = factor(type))) +
  ggplot2::geom_bar(stat = "identity",
                    position = "dodge") +
  ggplot2::scale_fill_manual(values = c(bold_pal[["Dark Slate Blue"]],
                                        pastel_pal[["Light Pink"]],
                                        pastel_pal[["Maximum Blue Purple"]])) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5),
                 legend.position = "none")
```

```{r three-month}
set.seed(3)
three_month_sub_data <-
  data.frame(x = sort(rep(seq(1:20), 2)))
three_month_sub_data$y <- 
  three_month_sub_data$x + 
  runif(n = length(three_month_sub_data$x),
        max = 5)
three_month_sub_data$type <- rep(seq(1,2))
three_month_sub_data$y[three_month_sub_data$type == 1] <-
  three_month_sub_data$y[three_month_sub_data$type == 1] + 6 + 
  three_month_sub_data$x[three_month_sub_data$type == 1]


ggplot2::ggplot(data = three_month_sub_data,
                mapping = ggplot2::aes(x = x, 
                                       y = y,
                                       color = factor(type),
                                       group = factor(type))) +
  ggplot2::geom_line(size = 10) +
  ggplot2::scale_color_manual(values = c(bold_pal[["Medium Aquamarine"]],
                                         bold_pal[["Inchworm"]])) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5),
                 legend.position = "none")
```

```{r histogram}
set.seed(20)
six_month_data <- data.frame(value = rnorm(n = 100, mean = 5, sd = 0.5))
ggplot2::ggplot(data = six_month_data,
                mapping = ggplot2::aes(x = value)) +
  ggplot2::geom_histogram(bins = 6, fill = bold_pal[["Sandy Brown"]]) +
  ggplot2::theme_classic() +
    ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5))
```

```{r nine-month}
set.seed(100)
nine_month_data <- 
  data.frame(value = c(rnorm(n = 10, mean = 5, sd= 3), 1, 1.5, 9))
ggplot2::ggplot(data = nine_month_data,
                 mapping = ggplot2::aes(x = value)) +
  ggplot2::geom_boxplot(size = 5, color = bold_pal[["Keppel"]]) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5))
```

```{r one-year, options}
set.seed(100)
nine_month_data <- 
  data.frame(x = c(rnorm(n = 100, mean = 5, sd = 4), 2, 2),
             y = c(rnorm(n = 100, mean = 5, sd = 2), 10, 0))
ggplot2::ggplot(data = nine_month_data,
                 mapping = ggplot2::aes(x = x, y = y)) +
  ggplot2::geom_violin(size = 5, color = bold_pal[["Keppel"]]) +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5))
```

```{r one-year-option2}
t <- pracma::deg2rad(seq(0, 360, by = 2))
pracma::polar(t, 
              cos(2*t), 
              bxcol = "white", 
              col = pastel_pal[["Light Pink"]], 
              main = "Sine and Cosine")
pracma::polar(t, sin(2*t), col = pastel_pal[["Light Pink"]], add = TRUE) 
```

```{r one-year-opt-3}
pie <- 
  ggplot2::ggplot(data = mtcars, 
                  mapping = ggplot2::aes(x = factor(1), 
                                         fill = factor(cyl))) +
  ggplot2::geom_bar(width = 1)+
  ggplot2::coord_polar(theta = "y") +
  ggplot2::scale_fill_manual(values = 
                               c(bold_pal[["Blue Munsell"]],
                                 pastel_pal[["Celeste"]],
                                 pastel_pal[["Baby Blue Eyes"]]))
  ggplot2::theme_minimal() +
  ggplot2::theme(legend.position = "none",
                 axis.text = ggplot2::element_blank(),
                 axis.ticks = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.line = ggplot2::element_line(size = 5))

pie
```
