---
title: "Pokemon EDA"
author: "Afton Coombs"
date: "12/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

```{r load-data}
## This dataset comes from: https://www.kaggle.com/rounakbanik/pokemon
## TODO: Get data programatically
pokedata <- readr::read_csv("pokemon/pokemon.csv")
```

```{r get-summary-of-data}
summary(pokedata)
```
```{r explore-weird-cols}
unique(pokedata$capture_rate)
```

```{r attr-pair-plot}
pokedata_attr <-
  pokedata %>%
  dplyr::select(attack,
                defense,
                hp,
                sp_attack,
                sp_defense,
                speed,
                height_m,
                weight_kg)
GGally::ggpairs(pokedata_attr)
```

```{r non-legend-attr-pair-plot}
non_legend_attr <- 
  pokedata_attr[pokedata$is_legendary == 0, ]
GGally::ggpairs(non_legend_attr)
```
```{r defense-pair-plot}
defense_data <-
  pokedata %>%
  dplyr::select(dplyr::contains("against"))
GGally::ggpairs(defense_data)
```

```{r table-types-1}
table(pokedata$type1)
```

```{r table-types-2}
table(pokedata$type2)
```

```{r prep-type-data}
type_data <-
  pokedata %>% 
  dplyr::select(name, generation, type1, type2) %>%
  dplyr::mutate(type2 = ifelse(test = is.na(type2),
                               yes = "_none_",
                               no = type2))
type_data_no_na <-
  pokedata %>% 
  dplyr::select(name, generation, type1, type2)

get_two_type_props <- function(type_data) {
  type1_props <-
    type_data %>%
    dplyr::filter(!is.na(type1)) %>%
    dplyr::group_by(type1) %>%
    dplyr::summarize(type_1_count = dplyr::n()) %>%
    dplyr::mutate(type_1_prop = 
                    type_1_count / 
                    sum(type_1_count, na.rm = TRUE))
  
  type2_props <-
    type_data %>%
    dplyr::filter(!is.na(type2)) %>%
    dplyr::group_by(type2) %>%
    dplyr::summarize(type_2_count = dplyr::n()) %>%
    dplyr::mutate(type_2_prop = 
                    type_2_count / 
                    sum(type_2_count, na.rm = TRUE))
  
  type_props <-
    type1_props %>%
    dplyr::full_join(type2_props, 
                     by = c("type1" = "type2")) %>%
    dplyr::select(type = type1, dplyr::everything()) %>%
    dplyr::select(-dplyr::contains("count")) %>%
    tidyr::pivot_longer(cols = 
                          c(type_1_prop, type_2_prop)) %>%
    dplyr::mutate(name = gsub(pattern = "_prop",
                              replacement = "",
                              name)) %>%
    dplyr::mutate(name = gsub(pattern = "_",
                              replacement = " ",
                              name)) %>%
    dplyr::select(type, type_level = name, prop = value)
  
  return(type_props)
}

type_props <- get_two_type_props(type_data)
type_props_no_na <- get_two_type_props(type_data_no_na)
```

```{r plot-type-1}
ggplot2::ggplot(data = type_data,
                mapping = ggplot2::aes(x = type1)) +
  ggplot2::geom_bar(stat = "count") +
  ggplot2::theme(axis.text.x = 
                  ggplot2::element_text(angle = 45))
```

```{r plot-type-2}
ggplot2::ggplot(data = type_data,
                mapping = ggplot2::aes(x = type2)) +
  ggplot2::geom_bar(stat = "count") +
  ggplot2::theme(axis.text.x = 
                  ggplot2::element_text(angle = 45))
```
```{r create-palete}
convert_to_6_digit_hex <- function(hex) {
  keep_names <- names(hex)
  hex <- paste0("#",
                substr(hex, 2, 2), 
                substr(hex, 2, 2), 
                substr(hex, 3, 3),
                substr(hex, 3, 3),
                substr(hex, 4, 4),
                substr(hex, 4, 4))
  names(hex) <- keep_names
  
  return(hex)
}

## These hex codes were copied from the pokemon type icons
## on this website: https://pokemondb.net/
pokepal <- 
  c("normal type 1" = "#aa9",
    "fire type 1" = "#f42",
    "water type 1" = "#39f",
    "electric type 1" = "#fc3",
    "grass type 1" = "#7c5",
    "ice type 1" = "#6cf",
    "fighting type 1" = "#b54",
    "poison type 1" = "#a59",
    "ground type 1" = "#db5",
    "flying type 1" = "#89f",
    "psychic type 1" = "#f59",
    "bug type 1" = "#ab2",
    "rock type 1" = "#ba6",
    "ghost type 1" = "#66b",
    "dragon type 1" = "#76e",
    "dark type 1" = "#754",
    "steel type 1" = "#aab",
    "fairy type 1" = "#e9e") %>%
  convert_to_6_digit_hex()

shades::swatch(pokepal)
```

```{r create-second-palette}
pokepal_2 <- 
  pokepal %>%
  shades::opacity(0.5)

shades::swatch(pokepal_2)
names(pokepal_2) <- 
  gsub(pattern = "1", replacement = "2", x = names(pokepal))

pokepal <- c(pokepal, pokepal_2)
```

```{r plot-types-side-by-side}
ggplot2::ggplot(data = type_props,
                mapping = 
                  ggplot2::aes(x = type,
                               y = prop,
                               group = type_level,
                               fill = type)) + 
  ggplot2::geom_bar(stat = "identity",
                    position = ggplot2::position_dodge())+
  ggplot2::theme(axis.text.x = 
                  ggplot2::element_text(angle = 45))
```
```{r show-colors-for-reference}
shades::swatch(pokepal)
```

```{r plot-types-side-by-side-no-na}
type_props_no_na <-
  type_props_no_na %>%
  dplyr::mutate(pal = paste0(type, " ", type_level))

ggplot2::ggplot(data = type_props_no_na,
                mapping = 
                  ggplot2::aes(x = type,
                               y = prop,
                               group = pal,
                               fill = pal)) + 
  ggplot2::geom_bar(stat = "identity",
                    position = ggplot2::position_dodge())+
  ggplot2::scale_fill_manual(values = pokepal) +
  ggplot2::labs(x = "Type", 
                y = "Proportion",
                title = "Pokemon Type Proportions") +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = 
                  ggplot2::element_text(angle = 45,
                                        size = 6))
```
