---
title: "Girl Scout Cookie"
author: "Afton Coombs"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

## Intro
Which Girl Scout Cookie is the most nutritious? If you were to eat one cookie
and only one for the whole day, which would bring you closes to the FDA 
guidelines?

```{r load-data}
gsc <- readr::read_csv("gsc_nutrition_facts.csv")
fda <- readr::read_csv("fda_guidelines.csv")
gsc_colors <- readr::read_csv("cookie_box_colors.csv")
```

```{r fix-fda}
fda <-
  fda %>%
  dplyr::mutate(Nutrient = ifelse(test = Nutrient == "Fat",
                                  yes = "Total Fat",
                                  no = Nutrient)) %>%
  dplyr::mutate(Nutrient = ifelse(test = Nutrient == "Total carbohydrate",
                                  yes = "Total Carbohydrate",
                                  no = Nutrient)) %>%
  dplyr::mutate(Nutrient = ifelse(test = Nutrient == "Saturated fat",
                                  yes = "Saturated Fat",
                                  no = Nutrient)) %>%
  dplyr::mutate(Nutrient = ifelse(test = Nutrient == "Added sugars",
                                  yes = "Total Sugars",
                                  no = Nutrient)) %>%
   dplyr::mutate(units_dv = gsub(pattern = "[0-9]",
                                replacement = "",
                                x = DV)) %>%
  dplyr::mutate(DV = as.numeric(gsub(pattern = "[A-Za-z]",
                                     replacement = "",
                                     x = DV)))
```

```{r separate-the-units}
fda_as_cookie <- 
  fda %>%
  dplyr::mutate(Name = "FDA Guidelines") %>%
  dplyr::filter(Nutrient %in% gsc$Nutrient) %>%
  dplyr::select(Name, Nutrient, Value = DV, units = units_dv)

gsc_and_fda <- 
  gsc %>%
  dplyr::mutate(units = gsub(pattern = "[0-9]", 
                             replacement = "", 
                             x = Value)) %>%
  dplyr::mutate(Value = as.numeric(gsub(pattern = "[A-Za-z]", 
                                        replacement = "", 
                                        x = Value))) %>%
  dplyr::mutate(Value = ifelse(test = Nutrient == "Calcium",
                               yes = Value / 100,
                               no = Value),
                units = ifelse(test = Nutrient == "Calcium",
                               yes = "mg",
                               units)) %>%
  dplyr::full_join(fda_as_cookie, 
                   by = c("Name", "Nutrient", "Value", "units")) %>%
  dplyr::inner_join(fda, by = "Nutrient") %>%
  dplyr::mutate(units = gsub(pattern = "\\.",
                             replacement = "",
                             x = units)) %>%
  dplyr::mutate(DV = as.numeric(DV)) %>%
  dplyr::mutate(percentage_dv_for_10_cookies = 
                  ifelse(test = Name != "FDA Guidelines",
                         yes = Value * 10 / DV * 100,
                         no = Value / DV * 100))
```

```{r get-dist}
get_dist_from_fda <- function(data, 
                              method = "manhattan", 
                              min_cookies = 5, 
                              max_cookies = 20) {
  fda_for_comp <- 
    data %>% 
    dplyr::filter(Name == "FDA Guidelines") %>% 
    dplyr::select(fda_comp = percentage_dv_for_10_cookies)
  
  fda_comp_along <- 
    rep(x = fda_for_comp$fda_comp, nrow(data) / nrow(fda_for_comp))
  
  data$fda_comp <- fda_comp_along
  
  all_cookies_distances <- 
    data.frame(Name = character(), x_cookies = numeric(), dist = numeric())
  
  for (i in unique(data$Name)) {
    one_cookie_comp <- 
      cbind(data %>% dplyr::filter(Name == i), fda_for_comp)
    
    dist_so_far <- data.frame("Name" = i, "x_cookies" = NA, "dist" = 100000000)
    
    lesser_dist_found <- TRUE
    
    while(lesser_dist_found) {
      for (j in seq(from = min_cookies, to = max_cookies, by = 1)) {
        one_cookie_next_comp <- 
          one_cookie_comp %>% 
          dplyr::select(Name, percentage_dv_for_10_cookies) %>%
          dplyr::mutate(percentage_dv_for_x_cookies = 
                          percentage_dv_for_10_cookies * (j/10),
                        x_cookies = j) %>%
          cbind(fda_for_comp) %>%
          dplyr::mutate(diff = 
                          abs(percentage_dv_for_x_cookies - fda_comp)) %>%
          dplyr::group_by(Name, x_cookies) %>%
          dplyr::summarize(dist = sum(diff), .groups = "keep")
        
        if (one_cookie_next_comp$dist < dist_so_far$dist) {
          lesser_dist_found <- TRUE
          dist_so_far <- one_cookie_next_comp
        } else { lesser_dist_found <- FALSE }
      }
    }
    all_cookies_distances <- 
      all_cookies_distances %>% 
      dplyr::full_join(dist_so_far, by = c("Name", "x_cookies", "dist"))
  }
  
  return(all_cookies_distances)
}

cookie_dists <- get_dist_from_fda(gsc_and_fda)
gsc_and_fda_with_dists <- 
  gsc_and_fda %>% dplyr::left_join(cookie_dists, by = "Name") %>%
  dplyr::mutate(percentage_dv_for_x_cookies = 
                  percentage_dv_for_10_cookies * x_cookies/10)
```

```{r pivot-cookies-wider}
gsc_and_fda_wide <- 
  gsc_and_fda_with_dists %>%
  dplyr::select(Name, Nutrient, percentage_dv_for_x_cookies) %>%
  tidyr::pivot_wider(names_from = Nutrient,
                     values_from = percentage_dv_for_x_cookies)
```

```{r get-gsc-colors}
gsc_pal <- c(gsc_colors$Hex, "#006400")
names(gsc_pal) <- c(gsc_colors$Name, "FDA Guidelines")
shades::swatch(gsc_pal)
```

```{r make-everything-radar-chart}
ggradar::ggradar(plot.data = gsc_and_fda_wide,
                 base.size = 4,
                 grid.label.size = 4,
                 axis.label.size = 3,
                 group.line.width = 1, 
                 group.point.size = 3,
                 legend.text.size = 6,
                 legend.position = "none",
                 values.radar = c("0%", 
                                  "100%",
                                  paste0(max(gsc_and_fda_with_dists$percentage_dv_for_x_cookies),
                                         "%")),
                 grid.max = max(gsc_and_fda_with_dists$percentage_dv_for_x_cookies),
                 grid.min = 0,
                 grid.mid = 100) +
  ggplot2::scale_color_manual(values = gsc_pal)
```

```{r get-radar-chart-max}
radar_max <- max(gsc_and_fda_wide %>% dplyr::select(where(is.numeric)))
radar_max
```
```{r make-charting-function}
make_cookie_comp_chart <- function(cookie_name, 
                                   cookie_data = gsc_and_fda_wide,
                                   distance_data = gsc_and_fda_with_dists,
                                   pal = gsc_pal,
                                   max = radar_max) {
  cookie_data <- 
    cookie_data %>% 
    dplyr::filter(Name %in% c(cookie_name, "FDA Guidelines"))
  
  distance_data <-
    distance_data %>%
    dplyr::filter(Name %in% c(cookie_name))
  
  distance <- unique(round(distance_data$dist, digits = 0))
  
  num_cookies <- unique(distance_data$x_cookies)
  
  d <- cowplot::draw_image(image = "peanut_butter_sandwich.jpg")
  
  g <- 
    ggradar::ggradar(plot.data = cookie_data,
                     values.radar = c("0%", 
                                      "100",
                                      paste0(radar_max, "%")),
                     grid.max = radar_max,
                     grid.min = 0,
                     grid.mid = 100,
                     legend.position = "bottom",
                     axis.label.size = 3,
                     legend.text.size = 8,
                     grid.label.size = 4,
                     background.circle.colour = "#000000",
                     background.circle.transparency = 0,
                     plot.extent.x.sf = 1.5, 
                     plot.extent.y.sf = 1.5,
                     group.line.width = 1,
                     group.point.size = 2) +
    ggplot2::scale_color_manual(values = pal) +
    ggplot2::geom_text(label = paste0("Distance: ", distance), 
                       x = 700, 
                       y = 400,
                       size = 3) +
    ggplot2::geom_text(label = paste0("Cookies: ", num_cookies), 
                       x = 700, 
                       y = 360,
                       size = 3)
  
  return(cowplot::ggdraw() + d + cowplot::draw_plot(g))
}

```

```{r chart-caramel-chocolate-chip}
make_cookie_comp_chart(cookie_name = "Caramel Chocolate Chip")
```

```{r caramel-delites}
make_cookie_comp_chart(cookie_name = "Caramel deLites")
```

```{r samoas}
make_cookie_comp_chart(cookie_name = "Samoas")
```

```{r choco-smores}
make_cookie_comp_chart(cookie_name = "Chocolate-Covered Girl Scout S'mores")
```

```{r regular-smores}
make_cookie_comp_chart(cookie_name = "Girl Scout S'mores")
```

```{r lemon-ups}
make_cookie_comp_chart(cookie_name = "Lemon-Ups")
```

```{r lemonades}
make_cookie_comp_chart(cookie_name = "Lemonades")
```

```{r peanut-butter-patties}
make_cookie_comp_chart(cookie_name = "Peanut Butter Patties")
```

```{r tagalongs}
make_cookie_comp_chart(cookie_name = "Tagalongs")
```

```{r thin-mints-abc}
make_cookie_comp_chart(cookie_name = "Thin Mints (ABC Baker)")
```

```{r thin-mints-brownie-baker}
make_cookie_comp_chart(cookie_name = "Thin Mints (Little Brownie Baker)")
```

```{r toast-yay}
make_cookie_comp_chart(cookie_name = "Toast Yay")
```

```{r do-si-dos}
make_cookie_comp_chart(cookie_name = "Do-si-dos")
```

```{r shortbread}
make_cookie_comp_chart(cookie_name = "Shortbread")
```

```{r trefoil}
make_cookie_comp_chart(cookie_name = "Trefoil")
```

```{r toffee-tastic}
make_cookie_comp_chart(cookie_name = "Toffee-tastic")
```

```{r loser}
gsc_and_fda_with_dists %>%
  dplyr::filter(dist == max(dist, na.rm = TRUE)) %>%
  dplyr::select(Name) %>%
  dplyr::distinct()
```

```{r winner}
gsc_and_fda_with_dists %>%
  dplyr::filter(Name != "FDA Guidelines") %>%
  dplyr::filter(dist == min(dist, na.rm = TRUE)) %>%
  dplyr::select(Name) %>%
  dplyr::distinct()
```

```{r ranked_cookies}
gsc_and_fda_with_dists_rank <-
  gsc_and_fda_with_dists %>%
  dplyr::select(Name, dist) %>%
  dplyr::arrange(dist) %>%
  dplyr::distinct()
```
