---
title: "HBCU"
author: "Afton Coombs"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

## Load data

```{r load-data}
## Copied from 
## https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-02-02/readme.md

# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2021-02-02')
tuesdata <- tidytuesdayR::tt_load(2021, week = 6)

hbcu_all <- tuesdata$hbcu_all
```

```{r clean-data}
## Also copied from 
## https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-02-02/readme.md

## Example cleaning script
hbcu_all <-
  hbcu_all %>%
  janitor::clean_names()


### Clean data ----------------------------------------------------------------
# We can separate by gender OR by program length and public/private, not both

### Gender breakdown
hbcu_by_gender <- 
  hbcu_all %>%
  # We only need year and gender columns
  dplyr::select(year, males, females) %>%
  # Convert to tidy format, collapsing male/female into one descriptor field
  tidyr::pivot_longer(males:females,
                      names_to = "gender",
                      values_to = "students") %>%
  # Convert from plural to singular for cleaner data
  # "s%" specifies an s character at the end of a string
  # ("$" is end of string in regular expressions)
  dplyr::mutate(gender = stringr::str_remove(gender, "s$"))


### Program breakdown
hbcu_by_program <- 
  hbcu_all %>%
  # We need fields with "public" or "private" in the name
  # (They also have 2- vs 4-year)
  # We DON'T need fields with "total" in the name, since this is redundant
  dplyr::select(year,
                dplyr::contains(c("public", "private")),
                -dplyr::contains("total")) %>%
  # names_pattern argument does the heavy lifting
  # It separates names into groups, as specified by parentheses "(group)"
  # Field names are structured so that program length is followed by public/private
  # We also specify "x_" as an optional argument using regular expressions
  tidyr::pivot_longer(cols = x4_year_public:x2_year_private,
                      names_pattern = "[x_]?(.*)_(.*)",
                      names_to = c("program_length", "public_private"),
                      values_to = "students") %>%
  dplyr::mutate(program_length = 
                  paste(readr::parse_number(program_length), "years"))
```

## Plotting!
```{r make-initial-graph}
g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender)) +
  ggplot2::geom_bar(stat = "identity")

g
```

```{r make-it-pretty}
blue_yellow_pal <- c("female" = "#FAD02C", "male"= "#333652")
muted_blue_yellow_pal <- 
  c("female" = "#DC9750", "male" = "#1E2640")
second_muted_blue_yellow_pal <-
  c("female" = "#90ADC6", "male" = "#1E2640")
g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender)) +
  ggplot2::geom_bar(stat = "identity") +
  ggplot2::scale_fill_manual(values = muted_blue_yellow_pal) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::theme_classic() +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 legend.position = "bottom")

g
```

```{r add-total-value}
g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students)) +
  ggplot2::geom_line(data = hbcu_all,
                     mapping = ggplot2::aes(x = year,
                                            y = total_enrollment + 12000),
                     color = "#F3EAC0",
                     size = 5) +
  ggplot2::geom_bar(data = hbcu_by_gender,
                    mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender),
                    stat = "identity") +
  ggplot2::scale_fill_manual(values = muted_blue_yellow_pal) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::theme_classic() +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 legend.position = "bottom")

g
```

```{r get-props}
props <-
  hbcu_all %>% 
  dplyr::select(year, males, females) %>%
  dplyr::mutate(proportion = females / males,
                sum = females + males)
```

```{r plot-with-labels}
offset <- 12000
line_color <- "#F3EAC0" #"#E9EAEC"  #"#F8E5E6"#"#ECE3F0" #"
prop_legend <- 
  data.frame(x = props$year[nrow(props)],
             y = props$sum[nrow(props)],
             label = "ratio")
fun_pal <-
  c("female" = "#F8C0C8", "male" = "#D3BBDD")

g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students)) +
  ggplot2::geom_line(data = hbcu_all,
                     mapping = ggplot2::aes(x = year,
                                            y = total_enrollment +
                                              offset),
                     color = line_color,
                     size = 7) +
  ggplot2::geom_bar(data = hbcu_by_gender,
                    mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender),
                    stat = "identity") +
  ggplot2::geom_label(data = props,
                      mapping = 
                        ggplot2::aes(x = year ,
                                     y = sum + offset,
                                     label = round(proportion, 
                                                   digits = 1)),
                      label.size = 0,
                      size = 1.5,
                      fill = line_color,) +
  ggplot2::geom_label(data = prop_legend,
                      mapping = ggplot2::aes(x = x,
                                             y = y,
                                             label = label),
                      nudge_x = 1.3,
                      nudge_y = offset,
                      size = 1.8,
                      label.size = 0,
                      fill = line_color) +
  ggplot2::scale_fill_manual(values =
                               muted_blue_yellow_pal) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::theme_classic() +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title = ggplot2::element_blank())

g
```

```{r blue-version}
line_color <- "#E9EAEC"  #"#F8E5E6"#"#ECE3F0" #"

fun_pal <-
  c("female" = "#F8C0C8", "male" = "#D3BBDD")

g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students)) +
  ggplot2::geom_line(data = hbcu_all,
                     mapping = ggplot2::aes(x = year,
                                            y = total_enrollment +
                                              offset),
                     color = line_color,
                     size = 7) +
  ggplot2::geom_bar(data = hbcu_by_gender,
                    mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender),
                    stat = "identity") +
  ggplot2::geom_label(data = props,
                      mapping = 
                        ggplot2::aes(x = year ,
                                     y = sum + offset,
                                     label = round(proportion, 
                                                   digits = 1)),
                      label.size = 0,
                      size = 1.5,
                      fill = line_color,) +
  ggplot2::geom_label(data = prop_legend,
                      mapping = ggplot2::aes(x = x,
                                             y = y,
                                             label = label),
                      nudge_x = 1.3,
                      nudge_y = offset,
                      size = 1.8,
                      label.size = 0,
                      fill = line_color) +
  ggplot2::scale_fill_manual(values =
                               second_muted_blue_yellow_pal) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::theme_classic() +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title = ggplot2::element_blank())

g
```

```{r pink-version}
line_color <- "#F8E5E6" # "#ECE3F0" # alternate line color

fun_pal <-
  c("female" = "#F8C0C8", "male" = "#D3BBDD")

g <- 
  ggplot2::ggplot(data = hbcu_by_gender,
                  mapping = ggplot2::aes(x = year,
                                         y = students)) +
  ggplot2::geom_line(data = hbcu_all,
                     mapping = ggplot2::aes(x = year,
                                            y = total_enrollment +
                                              offset),
                     color = line_color,
                     size = 7) +
  ggplot2::geom_bar(data = hbcu_by_gender,
                    mapping = ggplot2::aes(x = year,
                                         y = students,
                                         group = gender,
                                         fill = gender),
                    stat = "identity") +
  ggplot2::geom_label(data = props,
                      mapping = 
                        ggplot2::aes(x = year ,
                                     y = sum + offset,
                                     label = round(proportion, 
                                                   digits = 1)),
                      label.size = 0,
                      size = 1.5,
                      fill = line_color,) +
  ggplot2::geom_label(data = prop_legend,
                      mapping = ggplot2::aes(x = x,
                                             y = y,
                                             label = label),
                      nudge_x = 1.3,
                      nudge_y = offset,
                      size = 1.8,
                      label.size = 0,
                      fill = line_color) +
  ggplot2::scale_fill_manual(values =
                               fun_pal) +
  ggplot2::scale_y_continuous(labels = scales::comma) +
  ggplot2::theme_classic() +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 legend.position = "bottom",
                 axis.title = ggplot2::element_blank())

g
```
